[doc]
name = 'final_data'
# bundle = 'https://data1.fullyjustified.net/tlextras-2021.3r1.tar'
bundle = 'https://data1.fullyjustified.net/tlextras-2020.0r0.tar'

[[output]]
name = 'default'
type = 'pdf'
shell_escape = true
